# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: uv.esavi
canonical: https://paho.org/fhir/esavi
name: ESAVI
status: draft
version: 0.1.26
fhirVersion: 4.0.1
tittle: Guía de Implementación FHIR de ESAVI
copyrightYear: 2021+
releaseLabel: ci-build
#language: es-AR

jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
publisher:
  name: ESAVI -
  url: https://covid-19pharmacovigilance.paho.org/resources/updates-on-aefi
  email: rizzatodan@paho.org

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Inicio: index.html
  Objetivos: objetivos.html
  Alcance: alcance.html
  Uso: uso_como_llenar_guia.html
  Actores y Casos de Uso: actores_CasosUso.html
  Artefactos: artifacts.html
  Mapeos: mapeos.html
  #  Seguridad: seguridad.html
  Descargas: descargas.html
  Generalidades: generalidades.html
  Consideraciones: consideraciones.html
  #Datos Generales:
  #  Generalidades: generalidades.html
  #  Actores y Casos de Uso: actores_CasosUso.html
  #  Operaciones FHIR: operaciones.html
